version: 2
sources:
  - name: datafeed_shared_schema
    database: "{{('SALES_DEV')}}"
    schema: staging_layer

    tables:
      - name: stg_customers_data
      - name: stg_payments_data
      - name: stg_order_data
